[package]
name = "mdbook-gitbook"
version = "0.0.1"
authors = ["GeckoEidechse"]
edition = "2021"

description = "mdBook preprocessor to properly render GitBook specific syntax"
repository = "https://github.com/GeckoEidechse/mdbook-gitbook"
license = "MIT"
readme = "README.md"
keywords = [ "mdbook", "preprocessor", "markdown", "gitbook" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
mdbook = "0.4.36"
semver = "1.0.21"
serde_json = "1.0.111"
